### ISSUE TITLE
libsixel backend

### ISSUE THREAD

**Issue by atisharma** [ctorney/matplotlib-backend-sixel#1]
I've found [libsixel](https://github.com/libsixel/libsixel) to be superior to imagemagick, or at least much faster.

https://github.com/ctorney/matplotlib-backend-sixel/blob/592380fc46dee5988057c72c6bbc0a9d312acebc/matplotlib-backend-sixel/__init__.py#L23

```python
# imagemagick
p = Popen(["convert", "-colors", '16', 'png:-', 'sixel:-'], stdin=PIPE)

# libsixel
p = Popen(["img2sixel"], stdin=PIPE)
```

I understand there is also a python interface, if that were preferred.

**Comment by ctorney** [comment]
I don't think the difference is really noticeable and imagemagick is more widely used
